environment:
  global:
    PYTHON: "C:\\Python36-x64"
    PLATFORM: x64
    PYTEST_QT_API: "pyqt5"

install:


  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  # Upgrade to the latest version of pip to avoid it displaying warnings
  # about it being out of date.
  - "python -m pip install --upgrade pip"
  - "pip install pipenv --upgrade-strategy=only-if-needed"
  - "pipenv --python=3.6 install --dev ."
  - "pipenv run pip list"

build: false

test_script:
  - "pipenv run python -m pytest -v ./tests"

artifacts:
  - path: dist\*

skip_tags: true
